version: "3.4"

services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    env_file:
      - ".env"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql

  web:
    # build:
    #   context: "."
    #   args:
    #     - "FLASK_ENV=${FLASK_ENV:-production}"
    # env_file:
    #   - ".env"
    image: "gamer496/beehaz_web:latest"
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8000/healthy}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "${DOCKER_WEB_PORT:-127.0.0.1:8000}:8000"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
    volumes:
      - ./logs/:/var/log/
      - ./migrations/:/app/migrations

